package fi.riista.common.domain.observation

object MockObservationPageData {

    const val observationPageWithOneObservation =
        """
    {
      "content" : [ {
        "id" : 330,
        "rev" : 1,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 7035076,
          "longitude" : 483517,
          "source" : "GPS_DEVICE",
          "accuracy" : 12.302000045776367,
          "altitude" : 21.4,
          "altitudeAccuracy" : 0.6
        },
        "pointOfTime" : "2020-01-30T15:17:34.851",
        "description" : "This is description",
        "canEdit" : true,
        "imageIds" : [ "86f733ec-8105-48ab-80ce-727dbd1e7a96" ],
        "gameSpeciesCode" : 26440,
        "observationType" : "ULOSTE",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : 12,
        "verifiedByCarnivoreAuthority" : false,
        "observerName" : "Matti",
        "observerPhoneNumber" : "123456",
        "officialAdditionalInfo" : "Other info",
        "specimens" : [ {
          "id" : 192,
          "rev" : 0,
          "gender" : "FEMALE",
          "age" : "ADULT",
          "state" : "HEALTHY",
          "marking" : "COLLAR_OR_RADIO_TRANSMITTER",
          "widthOfPaw" : 5.5,
          "lengthOfPaw" : 6.6
        } ],
        "pack" : false,
        "litter" : false,
        "mobileClientRefId" : 6787724453918204169,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      } ],
      "latestEntry" : "2020-01-30T15:17:34.851",
      "hasMore" : false
    }
      """

    const val observationPageWithUpdatedObservation =
        """
    {
      "content" : [ {
        "id" : 330,
        "rev" : 2,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 7035077,
          "longitude" : 483518,
          "source" : "GPS_DEVICE",
          "accuracy" : 12.302000045776367,
          "altitude" : 21.4,
          "altitudeAccuracy" : 0.6
        },
        "pointOfTime" : "2020-03-30T15:17:34.851",
        "description" : "This is updated description",
        "canEdit" : false,
        "imageIds" : [ "86f733ec-8105-48ab-80ce-727dbd1e7a96", "a6997f26-dd4f-4687-8145-372365664798" ],
        "gameSpeciesCode" : 26441,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : 13,
        "verifiedByCarnivoreAuthority" : true,
        "observerName" : "Ville",
        "observerPhoneNumber" : "7654321",
        "officialAdditionalInfo" : "New info",
        "specimens" : [ {
          "id" : 192,
          "rev" : 1,
          "gender" : "MALE",
          "age" : "YOUNG",
          "state" : "HEALTHY",
          "marking" : "COLLAR_OR_RADIO_TRANSMITTER",
          "widthOfPaw" : 5.4,
          "lengthOfPaw" : 6.5
        } ],        
        "pack" : true,
        "litter" : true,
        "mobileClientRefId" : 6787724453918204169,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 2
      } ],
      "latestEntry" : "2020-03-30T15:17:34.851",
      "hasMore" : true
    }
      """

    const val observationPage =
        """
    {
      "content" : [ {
        "id" : 330,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 7035076,
          "longitude" : 483517,
          "source" : "GPS_DEVICE",
          "accuracy" : 12.302000045776367,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-01-30T15:17:34.851",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 26440,
        "observationType" : "ULOSTE",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : null,
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6787724453918204169,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : null
      }, {
        "id" : 404,
        "rev" : 2,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6861141,
          "longitude" : 358360,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-03-17T14:55:18.318",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "SYONNOS",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : null,
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6805159719309812157,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : null
      }, {
        "id" : 405,
        "rev" : 1,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6876863,
          "longitude" : 371014,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-03-18T21:27:00.147",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47240,
        "observationType" : "AANI",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6805631745410688778,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 406,
        "rev" : 1,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6826783,
          "longitude" : 313452,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2019-12-19T12:00:00.000",
        "description" : null,
        "canEdit" : false,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "mooselikeMaleAmount" : 2,
        "mooselikeFemaleAmount" : 3,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : null,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : true,
        "totalSpecimenAmount" : 5
      }, {
        "id" : 409,
        "rev" : 4,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6827299,
          "longitude" : 311816,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-03-25T12:00:00.000",
        "description" : "Xyzzy",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "OTHER",
        "deerHuntingTypeDescription" : "abe",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 0,
        "mooselikeFemale1CalfAmount" : 1,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : null,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 2
      }, {
        "id" : 408,
        "rev" : 4,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6825269,
          "longitude" : 312721,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-03-26T08:00:00.000",
        "description" : null,
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "OTHER",
        "mooselikeMaleAmount" : 1,
        "mooselikeFemaleAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : null,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 411,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6975064,
          "longitude" : 436470,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-03-31T15:46:54.410",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "DOG_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 1,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6810352750262616706,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 414,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6831214,
          "longitude" : 307732,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-01T12:00:00.000",
        "description" : null,
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "MOOSE_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 1,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : null,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 415,
        "rev" : 2,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6829118,
          "longitude" : 311622,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-03-29T13:00:00.000",
        "description" : null,
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47503,
        "observationType" : "NAKO",
        "observationCategory" : "MOOSE_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 1,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : null,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 412,
        "rev" : 4,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6854495,
          "longitude" : 331819,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-03-31T18:07:21.158",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "STAND_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 1,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6810388940858880474,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 410,
        "rev" : 4,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6870114,
          "longitude" : 366251,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-03-31T13:27:00.000",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "OTHER",
        "deerHuntingTypeDescription" : "juhuu",
        "mooselikeMaleAmount" : 1,
        "mooselikeFemaleAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6810316831733165156,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 416,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6868233,
          "longitude" : 363345,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-15T09:43:51.380",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "STAND_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 1,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6815825469557623509,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 417,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6854459,
          "longitude" : 334272,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-15T11:59:45.386",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "OTHER",
        "deerHuntingTypeDescription" : "jei!",
        "mooselikeMaleAmount" : 1,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6815860491050735098,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 418,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6832388,
          "longitude" : 343374,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-16T20:55:10.980",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "OTHER",
        "deerHuntingTypeDescription" : "jep",
        "mooselikeMaleAmount" : 1,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6816369550917227983,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 420,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6848227,
          "longitude" : 355389,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-17T15:28:23.124",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "DOG_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 1,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6816656424113724396,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 421,
        "rev" : 2,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6841741,
          "longitude" : 350184,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-23T12:02:00.000",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "STAND_HUNTING",
        "mooselikeMaleAmount" : 1,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6818829950637816439,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 424,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6854833,
          "longitude" : 364770,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-23T17:00:00.000",
        "description" : null,
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47503,
        "observationType" : "NAKO",
        "observationCategory" : "MOOSE_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 1,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : null,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 329,
        "rev" : 2,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6985983,
          "longitude" : 449348,
          "source" : "GPS_DEVICE",
          "accuracy" : 5.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-01-10T15:30:59.108",
        "description" : "Test",
        "canEdit" : true,
        "imageIds" : [ "027d7d5c-3374-4038-8d0b-cdc24a94fcee" ],
        "gameSpeciesCode" : 50106,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6780306211090706556,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 426,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6816136,
          "longitude" : 332385,
          "source" : "GPS_DEVICE",
          "accuracy" : 65.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-24T11:00:51.333",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "95f59dcc-cfb8-47cc-a0b1-3971aa34843b" ],
        "gameSpeciesCode" : 47503,
        "observationType" : "NAKO",
        "observationCategory" : "MOOSE_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 3,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6819185081264370457,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 3
      }, {
        "id" : 423,
        "rev" : 1,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6860006,
          "longitude" : 372463,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-23T13:00:00.000",
        "description" : null,
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : null,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 429,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6838991,
          "longitude" : 340860,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-08T10:06:00.000",
        "description" : "Ggj",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "OTHER",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 3,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6823252942364949173,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 3
      }, {
        "id" : 428,
        "rev" : 4,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6884952,
          "longitude" : 366286,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-04T16:11:00.000",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "86f733ec-8105-48ab-80ce-727dbd1e7a96", "a6997f26-dd4f-4687-8145-372365664798" ],
        "gameSpeciesCode" : 47503,
        "observationType" : "NAKO",
        "observationCategory" : "MOOSE_HUNTING",
        "mooselikeMaleAmount" : 2,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6822975966120863429,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 2
      }, {
        "id" : 427,
        "rev" : 3,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6985983,
          "longitude" : 449348,
          "source" : "GPS_DEVICE",
          "accuracy" : 5.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-04-24T13:08:00.000",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 26440,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ {
          "id" : 192,
          "rev" : 0,
          "gender" : "FEMALE",
          "age" : "ADULT",
          "state" : null,
          "marking" : null,
          "widthOfPaw" : null,
          "lengthOfPaw" : null
        } ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6819217950556808947,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 430,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6871524,
          "longitude" : 357503,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-08T14:38:31.416",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "84fbc264-d5a4-495b-afc7-657f5dd636db" ],
        "gameSpeciesCode" : 47503,
        "observationType" : "NAKO",
        "observationCategory" : "MOOSE_HUNTING",
        "mooselikeMaleAmount" : 1,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6824436362248867471,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 431,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6888643,
          "longitude" : 395415,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-11T15:20:41.743",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "4327322a-4287-45c9-a89d-3cc6b3390931" ],
        "gameSpeciesCode" : 47282,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6825560483036370358,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 432,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6796331,
          "longitude" : 309617,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-12T12:00:00.000",
        "description" : null,
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "MOOSE_HUNTING",
        "mooselikeMaleAmount" : 1,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 0,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : null,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 433,
        "rev" : 1,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6892044,
          "longitude" : 395152,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-12T16:37:02.350",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "JALKI",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ {
          "id" : 193,
          "rev" : 0,
          "gender" : null,
          "age" : "ADULT",
          "state" : null,
          "marking" : null,
          "widthOfPaw" : null,
          "lengthOfPaw" : null
        } ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6825951243687001521,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 434,
        "rev" : 3,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6889271,
          "longitude" : 397025,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-12T16:38:17.984",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47507,
        "observationType" : "NAKO",
        "observationCategory" : "MOOSE_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 1,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6825951568820195634,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 3
      }, {
        "id" : 436,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6928588,
          "longitude" : 404023,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-13T14:50:53.035",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "10e53d48-c5fe-4dfb-9225-bede1fce1553" ],
        "gameSpeciesCode" : 26427,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6826294974340194171,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 437,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6919004,
          "longitude" : 402036,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-13T14:51:17.912",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "fddd245d-16c0-44dc-908f-b6d9f81fd65d" ],
        "gameSpeciesCode" : 27152,
        "observationType" : "RIISTAKAMERA",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ {
          "id" : 196,
          "rev" : 0,
          "gender" : "MALE",
          "age" : null,
          "state" : null,
          "marking" : null,
          "widthOfPaw" : null,
          "lengthOfPaw" : null
        } ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6826295079706946999,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 438,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6918085,
          "longitude" : 397899,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-13T14:52:03.154",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "43df2105-f957-435a-901d-66d141c4a2d1" ],
        "gameSpeciesCode" : 26419,
        "observationType" : "RIISTAKAMERA",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6826295276891309965,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 439,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6933499,
          "longitude" : 409650,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-13T14:54:20.711",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "4c0f30ec-1f60-456c-acc4-f920abc55551" ],
        "gameSpeciesCode" : 26388,
        "observationType" : "RIISTAKAMERA",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6826295865423836554,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 440,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6931792,
          "longitude" : 430653,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-13T14:54:52.392",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "c7b904bb-2192-4304-950f-6190d7f49816" ],
        "gameSpeciesCode" : 26442,
        "observationType" : "RIISTAKAMERA",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6826296002230554041,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 441,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6925365,
          "longitude" : 407674,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-13T14:55:32.674",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "5f4f29b1-7602-4f1a-a8f6-a94433292a07" ],
        "gameSpeciesCode" : 26382,
        "observationType" : "RIISTAKAMERA",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6826296172278756556,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 443,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6975064,
          "longitude" : 436470,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-14T14:16:51.032",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47629,
        "observationType" : "NAKO",
        "observationCategory" : "DEER_HUNTING",
        "deerHuntingType" : "OTHER",
        "deerHuntingTypeDescription" : "abc",
        "mooselikeMaleAmount" : 1,
        "mooselikeFemaleAmount" : 1,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 3,
        "mooselikeFemale2CalfsAmount" : 1,
        "mooselikeFemale3CalfsAmount" : 6,
        "mooselikeFemale4CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6826657289540878601,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 35
      }, {
        "id" : 442,
        "rev" : 2,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6957191,
          "longitude" : 404802,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-14T14:13:19.212",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "dc6a548f-56d1-495e-8e9b-a24113b76566" ],
        "gameSpeciesCode" : 46587,
        "observationType" : "RIISTAKAMERA",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ {
          "id" : 197,
          "rev" : 1,
          "gender" : "FEMALE",
          "age" : "ADULT",
          "state" : "HEALTHY",
          "marking" : "COLLAR_OR_RADIO_TRANSMITTER",
          "widthOfPaw" : null,
          "lengthOfPaw" : null
        }, {
          "id" : 198,
          "rev" : 0,
          "gender" : "MALE",
          "age" : "LT1Y",
          "state" : null,
          "marking" : null,
          "widthOfPaw" : null,
          "lengthOfPaw" : null
        }, {
          "id" : 199,
          "rev" : 0,
          "gender" : "UNKNOWN",
          "age" : null,
          "state" : null,
          "marking" : null,
          "widthOfPaw" : null,
          "lengthOfPaw" : null
        } ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6826656380112560422,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 4
      }, {
        "id" : 444,
        "rev" : 1,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6958785,
          "longitude" : 472166,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-20T13:43:00.000",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 26419,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ {
          "id" : 200,
          "rev" : 0,
          "gender" : "FEMALE",
          "age" : null,
          "state" : null,
          "marking" : null,
          "widthOfPaw" : null,
          "lengthOfPaw" : null
        }, {
          "id" : 201,
          "rev" : 0,
          "gender" : "MALE",
          "age" : null,
          "state" : null,
          "marking" : null,
          "widthOfPaw" : null,
          "lengthOfPaw" : null
        } ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6828875417811456160,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 2
      }, {
        "id" : 445,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 4620952,
          "longitude" : -2266372,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-27T16:45:30.028",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "95c6468f-9555-4b3d-91a4-96412db74b68" ],
        "gameSpeciesCode" : 26427,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6831519706387703144,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 446,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 4621070,
          "longitude" : -2265767,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-27T16:46:40.324",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "ff849d47-2adb-4d99-b5d3-d0ab4aec18a3" ],
        "gameSpeciesCode" : 27152,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6831520007155296495,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 447,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 4621072,
          "longitude" : -2265828,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-27T16:47:00.903",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 26419,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6831520090152909180,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 448,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 4620814,
          "longitude" : -2266061,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-27T16:47:13.630",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 26360,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6831520147637735079,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 449,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 4621187,
          "longitude" : -2265829,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-27T16:47:25.465",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 26373,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6831520200210085503,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 454,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6993534,
          "longitude" : 436450,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-29T15:17:50.796",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 47503,
        "observationType" : "NAKO",
        "observationCategory" : "MOOSE_HUNTING",
        "mooselikeMaleAmount" : 0,
        "mooselikeFemaleAmount" : 0,
        "mooselikeCalfAmount" : 0,
        "mooselikeFemale1CalfAmount" : 0,
        "mooselikeFemale2CalfsAmount" : 7,
        "mooselikeFemale3CalfsAmount" : 0,
        "mooselikeUnknownSpecimenAmount" : 0,
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6832239287745241051,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 21
      }, {
        "id" : 450,
        "rev" : 1,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 4621107,
          "longitude" : -2265845,
          "source" : "MANUAL",
          "accuracy" : 0.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-05-27T16:47:38.751",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 26388,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6831520256616225543,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 5
      }, {
        "id" : 632,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6816141,
          "longitude" : 332388,
          "source" : "GPS_DEVICE",
          "accuracy" : 10.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-06-09T06:43:09.073",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 26427,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6836188589346930351,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 633,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6816133,
          "longitude" : 332381,
          "source" : "GPS_DEVICE",
          "accuracy" : 10.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-06-09T07:02:18.283",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "9dca768f-a11a-4f49-9218-bbeac7d13555" ],
        "gameSpeciesCode" : 26427,
        "observationType" : "NAKO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6836193523380969367,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 634,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6816123,
          "longitude" : 332384,
          "source" : "GPS_DEVICE",
          "accuracy" : 10.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-06-09T07:22:12.022",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "2a41822b-673c-426d-a064-909fea4d7b7e" ],
        "gameSpeciesCode" : 26388,
        "observationType" : "KOIRAN_RIISTATYO",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6836198651620260627,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 635,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6816150,
          "longitude" : 332378,
          "source" : "GPS_DEVICE",
          "accuracy" : 10.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-06-09T07:25:36.271",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ ],
        "gameSpeciesCode" : 46587,
        "observationType" : "JALKI",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : [ ],
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6836199529113546093,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : 1
      }, {
        "id" : 636,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6816145,
          "longitude" : 332385,
          "source" : "GPS_DEVICE",
          "accuracy" : 10.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-06-09T07:35:06.076",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "bfd521cb-4a12-478b-b030-3657d6b9f82c" ],
        "gameSpeciesCode" : 47230,
        "observationType" : "ULOSTE",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : null,
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6836201975134346858,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : null
      }, {
        "id" : 637,
        "rev" : 0,
        "type" : "OBSERVATION",
        "geoLocation" : {
          "latitude" : 6816129,
          "longitude" : 332374,
          "source" : "GPS_DEVICE",
          "accuracy" : 10.0,
          "altitude" : null,
          "altitudeAccuracy" : null
        },
        "pointOfTime" : "2020-06-09T07:39:19.633",
        "description" : "",
        "canEdit" : true,
        "imageIds" : [ "83898de3-3cb0-4687-bf8d-cc1299c98639" ],
        "gameSpeciesCode" : 46587,
        "observationType" : "SYONNOS",
        "observationCategory" : "NORMAL",
        "inYardDistanceToResidence" : null,
        "verifiedByCarnivoreAuthority" : null,
        "observerName" : null,
        "observerPhoneNumber" : null,
        "officialAdditionalInfo" : null,
        "specimens" : null,
        "pack" : null,
        "litter" : null,
        "mobileClientRefId" : 6836203063853905049,
        "observationSpecVersion" : 4,
        "withinMooseHunting" : null,
        "linkedToGroupHuntingDay" : false,
        "totalSpecimenAmount" : null
      } ],
      "latestEntry" : "2020-06-09T07:39:31.647",
      "hasMore" : false
    }
        """

    const val deletedObservations =
        """
    {
        "latestEntry" : "2016-02-18T11:00:00.000",
        "entryIds" : [ 12 ]
    }
        """

    const val emptyDeletedObservations =
        """
    {
        "latestEntry" : null,
        "entryIds" : [ ]
    }
        """

}
