package fi.riista.mobile.ui

enum class AlertDialogId {
    MAP_VIEWER_POI_INFO,
    MAIN_ACTIVITY_LOGOUT_CONFIRMATION,
    MAIN_ACTIVITY_GPS_PROMPT,
    MAP_AREA_LIST_ACTIVITY_REMOVE_AREA,
    MAP_AREA_LIST_ACTIVITY_FETCH_AREA,
    MAP_AREA_LIST_ACTIVITY_AREA_ERROR_DIALOG,
    CREATE_GROUP_HARVEST_FRAGMENT_CREATE_OBSERVATION_QUESTION,
    CREATE_GROUP_HARVEST_FRAGMENT_HARVEST_SAVE_FAILED,
    EDIT_GROUP_HARVEST_FRAGMENT_CREATE_OBSERVATION_QUESTION,
    EDIT_GROUP_HARVEST_FRAGMENT_HARVEST_SAVE_FAILED,
    VIEW_GROUP_HARVEST_FRAGMENT_REJECT_HARVEST_QUESTION,
    VIEW_GROUP_HARVEST_FRAGMENT_OPERATION_FAILED,
    MODIFY_GROUP_HUNTING_DAY_FRAGMENT_HUNTING_DAY_SAVE_FAILED,
    CREATE_GROUP_OBSERVATION_FRAGMENT_SAVE_FAILED,
    EDIT_GROUP_OBSERVATION_FRAGMENT_OBSERVATION_SAVE_FAILED,
    VIEW_GROUP_OBSERVATION_FRAGMENT_REJECT_OBSERVATION_QUESTION,
    VIEW_GROUP_OBSERVATION_FRAGMENT_DIALOG_ID_OPERATION_FAILED,
    CREATE_HUNTING_CONTROL_EVENT_FRAGMENT_SAVE_FAILED,
    EDIT_HUNTING_CONTROL_EVENT_FRAGMENT_SAVE_FAILED,
    MODIFY_HUNTING_CONTROL_EVENT_FRAGMENT_ATTACHMENT_DOWNLOAD_CONFIRMATION,
    MODIFY_HUNTING_CONTROL_EVENT_FRAGMENT_DELETE_ATTACHMENT,
    MODIFY_HUNTING_CONTROL_EVENT_FRAGMENT_ADD_ATTACHMENT,
    VIEW_HUNTING_CONTROL_EVENT_FRAGMENT_ATTACHMENT_DOWNLOAD_CONFIRMATION,
    LOGIN_ACTIVITY_LOGIN_FAILED,
    LOGIN_FRAGMENT_OPERATION_FAILED,
    RESET_PASSWORD_FRAGMENT_OPERATION_FAILED,
    MY_DETAILS_HUNTING_CLUB_MEMBERSHIPS_FRAGMENT_OPERATION_FAILED,
    MY_DETAILS_HUNTING_CLUB_MEMBERSHIPS_FRAGMENT_REJECT_INVITATION_QUESTION,
    VIEW_SRVA_FRAGMENT_DELETE_ENTRY_CONFIRMATION,
    SHOOTING_TEST_EVENT_FRAGMENT_CLOSE_QUESTION,
    SHOOTING_TEST_EVENT_FRAGMENT_REOPEN_QUESTION,
    SHOOTING_TEST_REGISTER_FRAGMENT_SEARCH_WITH_HUNTER_NUMBER,
    SHOOTING_TEST_REGISTER_FRAGMENT_SEARCH_WITH_SSN,
    SHOOTING_TEST_USER_ATTEMPTS_ADAPTER_REMOVE_ATTEMPT_QUESTION,
    SHOOTING_TEST_PAYMENTS_FRAGMENT_PAYMENT_CONFIRM,
    UNREGISTER_OPERATION_FAILED,
    UNREGISTER_CONFIRM_UNREGISTRATION,
    ;

    val id: Int
        get() = this.ordinal

    companion object {
        fun fromInt(value: Int) = values()[value]
    }
}
