package fi.riista.common.helpers

import fi.riista.common.model.LocalDate
import fi.riista.common.resources.RR
import fi.riista.common.resources.StringProvider

class TestStringProvider: StringProvider {

    override fun getString(stringId: RR.string): String {
        return when (stringId) {
            RR.string.generic_yes -> "yes"
            RR.string.generic_no -> "no"
            RR.string.error_date_not_allowed -> "error_date_not_allowed"
            RR.string.error_datetime_in_future -> "error_datetime_in_future"
            RR.string.group_hunting_label_club -> "club"
            RR.string.group_hunting_label_season -> "season"
            RR.string.group_hunting_label_species -> "species"
            RR.string.group_hunting_label_hunting_group -> "hunting_group"
            RR.string.group_hunting_error_hunting_has_finished -> "hunting_has_finished"
            RR.string.group_hunting_error_time_not_within_hunting_day -> "error_time_not_within_hunting_day"
            RR.string.harvest_label_select_permit -> "select_permit"
            RR.string.harvest_label_permit_information -> "permit_information"
            RR.string.harvest_label_permit_required -> "permit_required"
            RR.string.harvest_label_wild_boar_feeding_place -> "feeding_place"
            RR.string.harvest_label_amount -> "amount"
            RR.string.harvest_label_grey_seal_hunting_method -> "grey_seal_hunting_method"
            RR.string.harvest_label_is_taiga_bean_goose -> "is_taiga_bean_goose"
            RR.string.harvest_label_description -> "description"
            RR.string.harvest_label_weight -> "weight"
            RR.string.harvest_label_hunting_day_and_time -> "hunting_day_and_time"
            RR.string.harvest_label_actor -> "actor"
            RR.string.harvest_label_author -> "author"
            RR.string.harvest_label_deer_hunting_type -> "deer_hunting_type"
            RR.string.harvest_label_deer_hunting_other_type_description -> "deer_hunting_other_type_description"
            RR.string.harvest_label_not_edible -> "not_edible"
            RR.string.harvest_label_weight_estimated -> "weight_estimated"
            RR.string.harvest_label_weight_measured -> "weight_measured"
            RR.string.harvest_label_fitness_class -> "fitness_class"
            RR.string.harvest_label_antlers_type -> "antlers_type"
            RR.string.harvest_label_antlers_width -> "antlers_width"
            RR.string.harvest_label_antler_points_left -> "antler_points_left"
            RR.string.harvest_label_antler_points_right -> "antler_points_right"
            RR.string.harvest_label_antlers_lost -> "antlers_lost"
            RR.string.harvest_label_antlers_girth -> "antlers_girth"
            RR.string.harvest_label_antler_shaft_width -> "antler_shaft_width"
            RR.string.harvest_label_antlers_length -> "antlers_length"
            RR.string.harvest_label_antlers_inner_width -> "antlers_inner_width"
            RR.string.harvest_label_alone -> "alone"
            RR.string.harvest_label_additional_information -> "additional_information"
            RR.string.harvest_label_additional_information_instructions -> "additional_information_instructions"
            RR.string.harvest_label_additional_information_instructions_white_tailed_deer -> "additional_information_instructions_white_tailed_deer"
            RR.string.group_hunting_observation_field_hunting_day_and_time -> "hunting_day_and_time"
            RR.string.group_hunting_observation_field_observation_type -> "observation_type"
            RR.string.group_hunting_observation_field_actor -> "actor"
            RR.string.group_hunting_observation_field_author -> "author"
            RR.string.group_hunting_observation_field_headline_specimen_details -> "specimen_details"
            RR.string.group_hunting_observation_field_mooselike_male_amount -> "male_amount"
            RR.string.group_hunting_observation_field_mooselike_female_amount -> "female_amount"
            RR.string.group_hunting_observation_field_mooselike_female_1calf_amount -> "female_1calf_amount"
            RR.string.group_hunting_observation_field_mooselike_female_2calf_amount -> "female_2calf_amount"
            RR.string.group_hunting_observation_field_mooselike_female_3calf_amount -> "female_3calf_amount"
            RR.string.group_hunting_observation_field_mooselike_female_4calf_amount -> "female_4calf_amount"
            RR.string.group_hunting_observation_field_mooselike_calf_amount -> "calf_amount"
            RR.string.group_hunting_observation_field_mooselike_unknown_specimen_amount -> "unknown_specimen_amount"
            RR.string.group_hunting_observation_field_mooselike_male_amount_within_deer_hunting -> "male_amount_within_deer_hunting"
            RR.string.group_hunting_observation_field_mooselike_female_amount_within_deer_hunting -> "female_amount_within_deer_hunting"
            RR.string.group_hunting_observation_field_mooselike_female_1calf_amount_within_deer_hunting -> "female_1calf_amount_within_deer_hunting"
            RR.string.group_hunting_observation_field_mooselike_female_2calf_amount_within_deer_hunting -> "female_2calf_amount_within_deer_hunting"
            RR.string.group_hunting_observation_field_mooselike_female_3calf_amount_within_deer_hunting -> "female_3calf_amount_within_deer_hunting"
            RR.string.group_hunting_observation_field_mooselike_female_4calf_amount_within_deer_hunting -> "female_4calf_amount_within_deer_hunting"
            RR.string.group_hunting_observation_field_mooselike_calf_amount_within_deer_hunting -> "calf_amount_within_deer_hunting"
            RR.string.group_hunting_observation_field_mooselike_unknown_specimen_amount_within_deer_hunting -> "unknown_specimen_amount_within_deer_hunting"
            RR.string.group_hunting_day_label_start_date_and_time -> "start_date_and_time"
            RR.string.group_hunting_day_label_end_date_and_time -> "end_date_and_time"
            RR.string.group_hunting_day_label_number_of_hunters -> "number_of_hunters"
            RR.string.group_hunting_day_label_hunting_method -> "hunting_method"
            RR.string.group_hunting_day_label_number_of_hounds -> "number_of_hounds"
            RR.string.group_hunting_day_label_snow_depth_centimeters -> "snow_depth_centimeters"
            RR.string.group_hunting_day_label_break_duration_minutes -> "break_duration_minutes"
            RR.string.group_hunting_day_no_breaks -> "no_breaks"
            RR.string.group_hunting_day_error_dates_not_within_permit -> "error_dates_not_within_permit"
            RR.string.group_hunting_message_no_hunting_days_but_can_create -> "no_hunting_days_but_can_create"
            RR.string.group_hunting_message_no_hunting_days -> "no_hunting_days"
            RR.string.group_hunting_message_no_hunting_days_deer -> "no_hunting_days_deer"
            RR.string.group_hunting_method_passilinja_koira_ohjaajineen_metsassa -> "passilinja_koira_ohjaajineen_metsassa"
            RR.string.group_hunting_method_hiipiminen_pysayttavalle_koiralle -> "hiipiminen_pysayttavalle_koiralle"
            RR.string.group_hunting_method_passilinja_ja_tiivis_ajoketju -> "passilinja_ja_tiivis_ajoketju"
            RR.string.group_hunting_method_passilinja_ja_miesajo_jaljityksena -> "passilinja_ja_miesajo_jaljityksena"
            RR.string.group_hunting_method_jaljitys_eli_naakiminen_ilman_passeja -> "jaljitys_eli_naakiminen_ilman_passeja"
            RR.string.group_hunting_method_vaijynta_kulkupaikoilla -> "vaijynta_kulkupaikoilla"
            RR.string.group_hunting_method_vaijynta_ravintokohteilla -> "vaijynta_ravintokohteilla"
            RR.string.group_hunting_method_houkuttelu -> "houkuttelu"
            RR.string.group_hunting_method_muu -> "muu"
            RR.string.group_hunting_proposed_group_harvest_specimen -> "specimen"
            RR.string.group_hunting_proposed_group_harvest_shooter -> "shooter"
            RR.string.group_hunting_proposed_group_harvest_actor -> "actor"
            RR.string.group_member_selection_select_hunter -> "select_hunter"
            RR.string.group_member_selection_select_observer -> "select_observer"
            RR.string.group_member_selection_search_by_name -> "search_by_name"
            RR.string.group_member_selection_name_hint -> "name_hint"
            RR.string.group_hunting_hunter_id -> "hunter_id"
            RR.string.group_hunting_enter_hunter_id -> "enter_hunter_id"
            RR.string.group_hunting_invalid_hunter_id -> "invalid_hunter_id"
            RR.string.group_hunting_searching_hunter_by_id -> "searching_hunter_by_id"
            RR.string.group_hunting_searching_observer_by_id -> "searching_observer_by_id"
            RR.string.group_hunting_hunter_search_failed -> "hunter_search_failed"
            RR.string.group_hunting_observer_search_failed -> "observer_search_failed"
            RR.string.group_hunting_other_hunter -> "other_hunter"
            RR.string.group_hunting_other_observer -> "other_observer"
            RR.string.deer_hunting_type_stand_hunting -> "stand_hunting"
            RR.string.deer_hunting_type_dog_hunting -> "dog_hunting"
            RR.string.deer_hunting_type_other -> "other"
            RR.string.harvest_antler_type_hanko -> "antler_type_hanko"
            RR.string.harvest_antler_type_lapio -> "antler_type_lapio"
            RR.string.harvest_antler_type_seka -> "antler_type_seka"
            RR.string.harvest_fitness_class_erinomainen -> "fitness_class_erinomainen"
            RR.string.harvest_fitness_class_normaali -> "fitness_class_normaali"
            RR.string.harvest_fitness_class_laiha -> "fitness_class_laiha"
            RR.string.harvest_fitness_class_naantynyt -> "fitness_class_naantynyt"
            RR.string.grey_seal_hunting_method_shot -> "grey_seal_hunting_method_shot"
            RR.string.grey_seal_hunting_method_captured_alive -> "grey_seal_hunting_method_captured_alive"
            RR.string.grey_seal_hunting_method_shot_but_lost -> "grey_seal_hunting_method_shot_but_lost"
            RR.string.harvest_report_state_sent_for_approval -> "harvest_report_state_sent_for_approval"
            RR.string.harvest_report_state_approved -> "harvest_report_state_approved"
            RR.string.harvest_report_state_rejected -> "harvest_report_state_rejected"
            RR.string.harvest_report_required -> "harvest_report_required"
            RR.string.harvest_permit_accepted -> "harvest_permit_accepted"
            RR.string.harvest_permit_proposed -> "harvest_permit_proposed"
            RR.string.harvest_permit_rejected -> "harvest_permit_rejected"
            RR.string.observation_type_nako -> "nako"
            RR.string.observation_type_poikue -> "poikue"
            RR.string.observation_type_pari -> "pari"
            RR.string.observation_type_jalki -> "jalki"
            RR.string.observation_type_uloste -> "uloste"
            RR.string.observation_type_aani -> "aani"
            RR.string.observation_type_riistakamera -> "riistakamera"
            RR.string.observation_type_koiran_riistatyo -> "koiran_riistatyo"
            RR.string.observation_type_maastolaskenta -> "maastolaskenta"
            RR.string.observation_type_kolmiolaskenta -> "kolmiolaskenta"
            RR.string.observation_type_lentolaskenta -> "lentolaskenta"
            RR.string.observation_type_haaska -> "haaska"
            RR.string.observation_type_syonnos -> "syonnos"
            RR.string.observation_type_kelomispuu -> "kelomispuu"
            RR.string.observation_type_kiimakuoppa -> "kiimakuoppa"
            RR.string.observation_type_makuupaikka -> "makuupaikka"
            RR.string.observation_type_pato -> "pato"
            RR.string.observation_type_pesa -> "pesa"
            RR.string.observation_type_pesa_keko -> "pesa_keko"
            RR.string.observation_type_pesa_penkka -> "pesa_penkka"
            RR.string.observation_type_pesa_seka -> "pesa_seka"
            RR.string.observation_type_soidin -> "soidin"
            RR.string.observation_type_luolasto -> "luolasto"
            RR.string.observation_type_pesimaluoto -> "pesimaluoto"
            RR.string.observation_type_lepailyluoto -> "lepailyluoto"
            RR.string.observation_type_pesimasuo -> "pesimasuo"
            RR.string.observation_type_muuton_aikainen_lepailyalue -> "muuton_aikainen_lepailyalue"
            RR.string.observation_type_riistankulkupaikka -> "riistankulkupaikka"
            RR.string.observation_type_poikueymparisto -> "poikueymparisto"
            RR.string.observation_type_vaihtelevarakenteinen_mustikkametsa -> "vaihtelevarakenteinen_mustikkametsa"
            RR.string.observation_type_kuusisekoitteinen_metsa -> "kuusisekoitteinen_metsa"
            RR.string.observation_type_vaihtelevarakenteinen_mantysekoitteinen_metsa -> "vaihtelevarakenteinen_mantysekoitteinen_metsa"
            RR.string.observation_type_vaihtelevarakenteinen_lehtipuusekoitteinen_metsa -> "vaihtelevarakenteinen_lehtipuusekoitteinen_metsa"
            RR.string.observation_type_suon_reunametsa -> "suon_reunametsa"
            RR.string.observation_type_hakomamanty -> "hakomamanty"
            RR.string.observation_type_ruokailukoivikko -> "ruokailukoivikko"
            RR.string.observation_type_leppakuusimetsa_tai_koivikuusimetsa -> "leppakuusimetsa_tai_koivikuusimetsa"
            RR.string.observation_type_ruokailupajukko_tai_koivikko -> "ruokailupajukko_tai_koivikko"
            RR.string.observation_type_muu -> "muu"
            RR.string.error_observation_specimen_amount_at_least_two -> "specimen_amount_at_least_two"
            RR.string.hunting_club_membership_invitations -> "membership_invitations"
            RR.string.hunting_club_memberships -> "memberships"
            RR.string.poi_location_group_type_sighting_place -> "sighting_place"
            RR.string.poi_location_group_type_mineral_lick -> "mineral_lick"
            RR.string.poi_location_group_type_feeding_place -> "feeding_place"
            RR.string.poi_location_group_type_other -> "other"
            RR.string.hunting_control_start_time -> "start_time"
            RR.string.hunting_control_end_time -> "end_time"
            RR.string.hunting_control_duration -> "duration"
            RR.string.hunting_control_event_type -> "event_type"
            RR.string.hunting_control_number_of_inspectors -> "number_of_inspectors"
            RR.string.hunting_control_cooperation_type -> "cooperation_type"
            RR.string.hunting_control_wolf_territory -> "wolf_territory"
            RR.string.hunting_control_inspectors -> "inspectors"
            RR.string.hunting_control_location_description -> "location_description"
            RR.string.hunting_control_event_description -> "event_description"
            RR.string.hunting_control_number_of_customers -> "number_of_customers"
            RR.string.hunting_control_number_of_proof_orders -> "number_of_proof_orders"
            RR.string.hunting_control_date -> "date"
            RR.string.hunting_control_other_participants -> "other_participants"
            RR.string.hunting_control_duration_zero -> "duration_zero"
            RR.string.hunting_control_choose_inspector -> "choose_inspector"
            RR.string.hunting_control_choose_cooperation -> "choose_cooperation"
            RR.string.hunting_control_inspector_selection_search_by_name -> "inspector_selection_search_by_name"
            RR.string.hunting_control_inspector_selection_name_hint -> "selection_name_hint"
            RR.string.hunting_control_error_no_inspectors_for_selected_date -> "no_inspectors_for_selected_date"
            RR.string.hunting_control_error_no_self_as_inspector -> "no_self_as_inspector"
            RR.string.hunting_control_attachments -> "attachments"
            RR.string.hunting_control_add_attachment -> "add_attachment"
            RR.string.hunting_control_cooperation_type_poliisi -> "cooperation_type_poliisi"
            RR.string.hunting_control_cooperation_type_rajavartiosto -> "cooperation_type_rajavartiosto"
            RR.string.hunting_control_cooperation_type_mh -> "cooperation_type_mh"
            RR.string.hunting_control_cooperation_type_oma -> "cooperation_type_oma"
            RR.string.hunting_control_event_type_mooselike -> "event_type_mooselike"
            RR.string.hunting_control_event_type_large_carnivore -> "event_type_large_carnivore"
            RR.string.hunting_control_event_type_grouse -> "event_type_grouse"
            RR.string.hunting_control_event_type_waterfowl -> "event_type_waterfowl"
            RR.string.hunting_control_event_type_dog_discipline -> "event_type_dog_discipline"
            RR.string.hunting_control_event_type_other -> "event_type_other"
            RR.string.srva_event_label_other_species_description -> "label_other_species_description"
            RR.string.srva_event_label_approver -> "label_approver"
            RR.string.srva_event_label_rejector -> "label_rejector"
            RR.string.srva_event_label_specimen_amount -> "label_specimen_amount"
            RR.string.srva_event_label_event_category -> "label_event_category"
            RR.string.srva_event_label_deportation_order_number -> "label_deportation_order_number"
            RR.string.srva_event_label_event_type -> "label_event_type"
            RR.string.srva_event_label_other_event_type_description -> "label_other_event_type_description"
            RR.string.srva_event_label_event_type_detail -> "label_event_type_detail"
            RR.string.srva_event_label_other_event_type_detail_description -> "label_other_event_type_detail_description"
            RR.string.srva_event_label_method -> "label_method"
            RR.string.srva_event_label_other_method_description -> "label_other_method_description"
            RR.string.srva_event_label_event_result -> "label_event_result"
            RR.string.srva_event_label_event_result_detail -> "label_event_result_detail"
            RR.string.srva_event_label_person_count -> "label_person_count"
            RR.string.srva_event_label_hours_spent -> "label_hours_spent"
            RR.string.srva_event_label_description -> "label_description"
            RR.string.srva_event_category_accident -> "category_accident"
            RR.string.srva_event_category_deportation -> "category_deportation"
            RR.string.srva_event_category_injured_animal -> "category_injured_animal"
            RR.string.srva_event_type_traffic_accident -> "type_traffic_accident"
            RR.string.srva_event_type_railway_accident -> "type_railway_accident"
            RR.string.srva_event_type_animal_near_houses_area -> "type_animal_near_houses_area"
            RR.string.srva_event_type_animal_at_food_destination -> "type_animal_at_food_destination"
            RR.string.srva_event_type_injured_animal -> "type_injured_animal"
            RR.string.srva_event_type_animal_on_ice -> "type_animal_on_ice"
            RR.string.srva_event_type_other -> "type_other"
            RR.string.srva_event_type_detail_cared_house_area -> "detail_cared_house_area"
            RR.string.srva_event_type_detail_farm_animal_building -> "detail_farm_animal_building"
            RR.string.srva_event_type_detail_urban_area -> "detail_urban_area"
            RR.string.srva_event_type_detail_carcass_at_forest -> "detail_carcass_at_forest"
            RR.string.srva_event_type_detail_carcass_near_houses_area -> "detail_carcass_near_houses_area"
            RR.string.srva_event_type_detail_garbage_can -> "detail_garbage_can"
            RR.string.srva_event_type_detail_beehive -> "detail_beehive"
            RR.string.srva_event_type_detail_other -> "detail_other"
            RR.string.srva_event_result_animal_found_dead -> "result_animal_found_dead"
            RR.string.srva_event_result_animal_found_and_terminated -> "result_animal_found_and_terminated"
            RR.string.srva_event_result_animal_found_and_not_terminated -> "result_animal_found_and_not_terminated"
            RR.string.srva_event_result_accident_site_not_found -> "result_accident_site_not_found"
            RR.string.srva_event_result_animal_not_found -> "result_animal_not_found"
            RR.string.srva_event_result_animal_terminated -> "result_animal_terminated"
            RR.string.srva_event_result_animal_deported -> "result_animal_deported"
            RR.string.srva_event_result_undue_alarm -> "result_undue_alarm"
            RR.string.srva_event_result_detail_animal_contacted_and_deported -> "detail_animal_contacted_and_deported"
            RR.string.srva_event_result_detail_animal_contacted -> "detail_animal_contacted"
            RR.string.srva_event_result_detail_uncertain_result -> "detail_uncertain_result"
            RR.string.srva_method_traced_with_dog -> "method_traced_with_dog"
            RR.string.srva_method_traced_without_dog -> "method_traced_without_dog"
            RR.string.srva_method_dog -> "method_dog"
            RR.string.srva_method_pain_equipment -> "method_pain_equipment"
            RR.string.srva_method_sound_equipment -> "method_sound_equipment"
            RR.string.srva_method_vehicle -> "method_vehicle"
            RR.string.srva_method_chasing_with_people -> "method_chasing_with_people"
            RR.string.srva_method_other -> "method_other"
            RR.string.other_species -> "other_species"
            RR.string.unknown_species -> "unknown_species"
            RR.string.gender_label -> "gender_label"
            RR.string.gender_female -> "gender_female"
            RR.string.gender_male -> "gender_male"
            RR.string.gender_unknown -> "gender_unknown"
            RR.string.age_label -> "age_label"
            RR.string.age_adult -> "age_adult"
            RR.string.age_young -> "age_young"
            RR.string.age_less_than_one_year -> "age_less_than_one_year"
            RR.string.age_between_one_and_two_years -> "age_between_one_and_two_years"
            RR.string.age_eraus -> "age_eraus"
            RR.string.age_unknown -> "age_unknown"
            RR.string.training_type_lahi -> "training_type_lahi"
            RR.string.training_type_sahkoinen -> "training_type_sahkoinen"
            RR.string.jht_training_occupation_type_metsastyksenvalvoja -> "occupation_type_metsastyksenvalvoja"
            RR.string.jht_training_occupation_type_metsastajatutkinnon_vastaanottaja -> "occupation_type_metsast"
            RR.string.jht_training_occupation_type_ampumakokeen_vastaanottaja -> "occupation_type_ampumakokeen_vastaanottaja"
            RR.string.jht_training_occupation_type_rhyn_edustaja_riistavahinkojen_maastokatselmuksessa -> "occupation_type_rhyn_edustaja_riistavahinkojen_maastokatselmuksessa"
            RR.string.occupation_training_occupation_type_petoyhdyshenkilo -> "occupation_type_petoyhdyshenkilo"
            RR.string.observation_label_observation_category -> "observation_category"
            RR.string.observation_label_within_moose_hunting -> "within_moose_hunting"
            RR.string.observation_label_within_deer_hunting -> "within_deer_hunting"
            RR.string.observation_label_amount -> "amount"
            RR.string.observation_label_tassu_verified_by_carnivore_authority -> "tassu_verified_by_carnivore_authority"
            RR.string.observation_label_tassu_observer_name -> "tassu_observer_name"
            RR.string.observation_label_tassu_observer_phonenumber -> "tassu_observer_phonenumber"
            RR.string.observation_label_tassu_official_additional_information -> "tassu_official_additional_information"
            RR.string.observation_label_tassu_in_yard_distance_to_residence -> "tassu_in_yard_distance_to_residence"
            RR.string.observation_label_tassu_litter -> "tassu_litter"
            RR.string.observation_label_tassu_pack -> "tassu_pack"
            RR.string.observation_label_description -> "description"
            RR.string.specimen_label_width_of_paw -> "width_of_paw"
            RR.string.specimen_label_length_of_paw -> "length_of_paw"
            RR.string.specimen_label_state_of_health -> "state_of_health"
            RR.string.specimen_label_marking -> "marking"
            RR.string.specimen_state_of_health_healthy -> "healthy"
            RR.string.specimen_state_of_health_ill -> "ill"
            RR.string.specimen_state_of_health_wounded -> "wounded"
            RR.string.specimen_state_of_health_carcass -> "carcass"
            RR.string.specimen_state_of_health_dead -> "dead"
            RR.string.specimen_marking_not_marked -> "not_marked"
            RR.string.specimen_marking_collar_or_radio_transmitter -> "collar_or_radio_transmitter"
            RR.string.specimen_marking_leg_ring_or_wing_tag -> "leg_ring_or_wing_tag"
            RR.string.specimen_marking_earmark -> "earmark"
            RR.string.observation_category_normal -> "normal"
            RR.string.observation_category_moose_hunting -> "moose_hunting"
            RR.string.observation_category_deer_hunting -> "deer_hunting"
            RR.string.hunting_control_hunter_details -> "hunter_details"
            RR.string.hunting_control_hunter_name -> "hunter_name"
            RR.string.hunting_control_hunter_date_of_birth -> "date_of_birth"
            RR.string.hunting_control_hunter_home_municipality -> "home_municipality"
            RR.string.hunting_control_hunter_number -> "hunter_id"
            RR.string.hunting_control_hunting_license -> "hunting_license"
            RR.string.hunting_control_hunting_license_status -> "hunting_license_status"
            RR.string.hunting_control_hunting_license_status_active -> "hunting_license_status_active"
            RR.string.hunting_control_hunting_license_status_inactive -> "hunting_license_status_inactive"
            RR.string.hunting_control_hunting_license_date_of_payment -> "hunting_license_date_of_payment"
            RR.string.hunting_control_shooting_tests -> "shooting_tests"
            RR.string.hunting_control_reset_hunter_info -> "reset"
            RR.string.hunting_control_hunter_not_found -> "hunter_not_found"
            RR.string.hunting_control_network_error -> "network_error"
            RR.string.hunting_control_retry -> "retry"
            RR.string.shooting_test_state_waiting_to_start -> "waiting_to_start"
            RR.string.shooting_test_state_ongoing -> "ongoing"
            RR.string.shooting_test_state_ongoing_ready_to_close -> "ready_to_close"
            RR.string.shooting_test_state_closed -> "closed"
            RR.string.shooting_test_type_moose -> "moose"
            RR.string.shooting_test_type_bear -> "bear"
            RR.string.shooting_test_type_roe_deer -> "deer"
            RR.string.shooting_test_type_bow -> "bow"
            RR.string.shooting_test_result_qualified -> "qualified"
            RR.string.shooting_test_result_unqualified -> "unqualified"
            RR.string.shooting_test_result_timed_out -> "timed_out"
            RR.string.shooting_test_result_rebated -> "rebated"
            RR.string.hunting_control_ssn -> "ssn"
            RR.string.hunting_control_searching_hunter -> "searching_hunter"
            RR.string.harvest_settings_add_harvest_for_other_hunter -> "add_harvest_for_other_hunter"
            RR.string.harvest_settings_add_harvest_for_other_hunter_explanation -> "add_harvest_for_other_hunter_explanation"
            RR.string.harvest_settings_enable_club_selection -> "enable_club_selection"
            RR.string.harvest_settings_enable_club_selection_explanation -> "enable_club_selection_explanation"
            RR.string.harvest_label_own_harvest -> "own_harvest"
            RR.string.harvest_label_hunting_club -> "hunting_club"
            RR.string.harvest_label_hunting_club_official_code -> "hunting_club_official_code"
            RR.string.hunting_club_selection_select_club -> "select_club"
            RR.string.hunting_club_selection_search_by_name -> "search_by_name"
            RR.string.hunting_club_selection_search_by_name_hint -> "search_by_name_hint"
            RR.string.hunting_club_selection_no_club_selection -> "no_club_selection"
            RR.string.hunting_club_selection_other_club -> "other_club"
            RR.string.hunting_club_search_enter_club_official_code -> "enter_club_official_code"
            RR.string.hunting_club_search_invalid_official_code -> "invalid_official_code"
            RR.string.hunting_club_search_searching_by_official_code -> "searching_by_official_code"
            RR.string.hunting_club_search_search_failed -> "search_failed"
            RR.string.sun_day_selection_label -> "day_selection_label"
            RR.string.sun_sunrise_label -> "sunrise_label"
            RR.string.sun_sunset_label -> "sunset_label"
            RR.string.sun_instructions -> "instructions"
            RR.string.sun_disclaimer -> "disclaimer"
        }
    }

    override fun getFormattedString(stringFormatId: RR.stringFormat, arg: String): String {
        return when (stringFormatId) {
            RR.stringFormat.group_hunting_label_permit_formatted -> "permit: $arg"
            else -> throw RuntimeException("1 string arg: unexpected stringFormatId ($stringFormatId) requested")
        }
    }

    override fun getFormattedString(stringFormatId: RR.stringFormat, arg1: String, arg2: String): String {
        return when (stringFormatId) {
            RR.stringFormat.generic_hours_and_minutes_format -> "$arg1 $arg2"
            else -> throw RuntimeException("2 string arg: unexpected stringFormatId ($stringFormatId) requested")
        }
    }

    override fun getFormattedDouble(stringFormatId: RR.stringFormat, arg: Double): String {
        return when (stringFormatId) {
            RR.stringFormat.double_format_one_decimal -> arg.toString().let { withAllDecimals ->
                withAllDecimals.substring(
                    startIndex = 0,
                    endIndex = withAllDecimals.lastIndexOf('.')
                        .takeIf { it != -1 }
                        ?.let { it + 2 }
                        ?.coerceAtMost(withAllDecimals.length)
                        ?: withAllDecimals.length
                )
            }
            RR.stringFormat.double_format_zero_decimals -> arg.toString().substringBefore('.')
            else -> throw RuntimeException("1 double arg: unexpected stringFormatId ($stringFormatId) requested")
        }
    }

    override fun getQuantityString(pluralsId: RR.plurals, quantity: Int, arg: Int): String {
        return when (pluralsId) {
            RR.plurals.hours -> if (quantity == 1) {
                "$arg hour"
            } else {
                "$arg hours"
            }
            RR.plurals.minutes -> if (quantity == 1) {
                "$arg minute"
            } else {
                "$arg minutes"
            }
            else -> throw RuntimeException("Unexpected pluralsId ($pluralsId) requested")
        }
    }

    override fun getFormattedDate(dateFormatId: RR.stringFormat, arg: LocalDate): String {
        return when (dateFormatId) {
            RR.stringFormat.date_format_short -> "${arg.dayOfMonth}.${arg.monthNumber}.${arg.year}"
            else -> throw RuntimeException("Unexpected dateFormatId ($dateFormatId) requested")
        }
    }

    companion object {
        val INSTANCE = TestStringProvider()
    }
}
